# Generated by Django 4.1.7 on 2023-05-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
