# Generated by Django 4.1.7 on 2023-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkapp', '0002_remove_product_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
