# Generated by Django 4.1.7 on 2023-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkapp', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
